data<-read.table("household_power_consumption.txt",sep=";",na.strings="?",header=T,stringsAsFactors=F)
data$Date<-as.Date(data$Date,"%d/%m/%Y")
feb07data<-subset(data,Date==as.Date("2007-02-01") | Date==as.Date("2007-02-02"))
feb07data$datetime<-paste(feb07data$Date,feb07data$Time)
feb07data$datetime<-strptime(feb07data$datetime,"%Y-%m-%d %H:%M:%S")
png("plot2.png")
with(feb07data, plot(datetime,Global_active_power, xlab="",ylab="Global Active Power (kilowatts)",type="n"))
with(feb07data, lines(datetime,Global_active_power))
dev.off()